# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "D:/Gimhan Sandeeptha/Gimhan/Semester 02/Computer Organization and Digital Design/Labs/Lab 10/Lab 10/.Xil/Vivado-31260-LAPTOP-J3LKM3K9/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7a35tcpg236-1

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common_vhdl.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_vhdl -lib xil_defaultlib {
      {D:/Gimhan Sandeeptha/Gimhan/Semester 02/Computer Organization and Digital Design/Labs/Lab 10/Lab 10/Lab 10.srcs/sources_1/imports/new/ALU.vhd}
      {D:/Gimhan Sandeeptha/Gimhan/Semester 02/Computer Organization and Digital Design/Labs/Lab 10/Lab 10/Lab 10.srcs/sources_1/imports/sources_1/new/Anode.vhd}
      {D:/Gimhan Sandeeptha/Gimhan/Semester 02/Computer Organization and Digital Design/Labs/Lab 10/Lab 10/Lab 10.srcs/sources_1/imports/new/BitShifter.vhd}
      {D:/Gimhan Sandeeptha/Gimhan/Semester 02/Computer Organization and Digital Design/Labs/Lab 10/Lab 10/Lab 10.srcs/sources_1/imports/new/Bitshiftleft.vhd}
      {D:/Gimhan Sandeeptha/Gimhan/Semester 02/Computer Organization and Digital Design/Labs/Lab 10/Lab 10/Lab 10.srcs/sources_1/imports/new/Bitshiftright.vhd}
      {D:/Gimhan Sandeeptha/Gimhan/Semester 02/Computer Organization and Digital Design/Labs/Lab 10/Lab 10/Lab 10.srcs/sources_1/imports/new/CMP.vhd}
      {D:/Gimhan Sandeeptha/Gimhan/Semester 02/Computer Organization and Digital Design/Labs/Lab 10/Lab 10/Lab 10.srcs/sources_1/imports/new/Combiner.vhd}
      {D:/Gimhan Sandeeptha/Gimhan/Semester 02/Computer Organization and Digital Design/Labs/Lab 10/Lab 10/Lab 10.srcs/sources_1/imports/new/Combiner_div.vhd}
      {D:/Gimhan Sandeeptha/Gimhan/Semester 02/Computer Organization and Digital Design/Labs/Lab 10/Lab 10/Lab 10.srcs/sources_1/imports/new/DFF.vhd}
      {D:/Gimhan Sandeeptha/Gimhan/Semester 02/Computer Organization and Digital Design/Labs/Lab 10/Lab 10/Lab 10.srcs/sources_1/imports/sources_1/new/Dec_2_to_4.vhd}
      {D:/Gimhan Sandeeptha/Gimhan/Semester 02/Computer Organization and Digital Design/Labs/Lab 10/Lab 10/Lab 10.srcs/sources_1/imports/sources_1/new/Dec_3_to_8.vhd}
      {D:/Gimhan Sandeeptha/Gimhan/Semester 02/Computer Organization and Digital Design/Labs/Lab 10/Lab 10/Lab 10.srcs/sources_1/imports/sources_1/imports/new/Decoder_2_to_4.vhd}
      {D:/Gimhan Sandeeptha/Gimhan/Semester 02/Computer Organization and Digital Design/Labs/Lab 10/Lab 10/Lab 10.srcs/sources_1/imports/sources_1/imports/new/Decoder_3_to_8.vhd}
      {D:/Gimhan Sandeeptha/Gimhan/Semester 02/Computer Organization and Digital Design/Labs/Lab 10/Lab 10/Lab 10.srcs/sources_1/imports/new/Divider.vhd}
      {D:/Gimhan Sandeeptha/Gimhan/Semester 02/Computer Organization and Digital Design/Labs/Lab 10/Lab 10/Lab 10.srcs/sources_1/imports/new/Divider_1bit.vhd}
      {D:/Gimhan Sandeeptha/Gimhan/Semester 02/Computer Organization and Digital Design/Labs/Lab 10/Lab 10/Lab 10.srcs/sources_1/imports/new/FA.vhd}
      {D:/Gimhan Sandeeptha/Gimhan/Semester 02/Computer Organization and Digital Design/Labs/Lab 10/Lab 10/Lab 10.srcs/sources_1/imports/new/HA.vhd}
      {D:/Gimhan Sandeeptha/Gimhan/Semester 02/Computer Organization and Digital Design/Labs/Lab 10/Lab 10/Lab 10.srcs/sources_1/imports/new/INS_DECO2.vhd}
      {D:/Gimhan Sandeeptha/Gimhan/Semester 02/Computer Organization and Digital Design/Labs/Lab 10/Lab 10/Lab 10.srcs/sources_1/imports/new/Inverter.vhd}
      {D:/Gimhan Sandeeptha/Gimhan/Semester 02/Computer Organization and Digital Design/Labs/Lab 10/Lab 10/Lab 10.srcs/sources_1/imports/sources_1/imports/new/LUT_16_7.vhd}
      {D:/Gimhan Sandeeptha/Gimhan/Semester 02/Computer Organization and Digital Design/Labs/Lab 10/Lab 10/Lab 10.srcs/sources_1/imports/sources_1/imports/sources_1/new/MUX_1_to_2.vhd}
      {D:/Gimhan Sandeeptha/Gimhan/Semester 02/Computer Organization and Digital Design/Labs/Lab 10/Lab 10/Lab 10.srcs/sources_1/imports/new/MUX_2_8.vhd}
      {D:/Gimhan Sandeeptha/Gimhan/Semester 02/Computer Organization and Digital Design/Labs/Lab 10/Lab 10/Lab 10.srcs/sources_1/imports/new/MUX_2_WAY_4bit.vhd}
      {D:/Gimhan Sandeeptha/Gimhan/Semester 02/Computer Organization and Digital Design/Labs/Lab 10/Lab 10/Lab 10.srcs/sources_1/imports/sources_1/new/MUX_2_to_1.vhd}
      {D:/Gimhan Sandeeptha/Gimhan/Semester 02/Computer Organization and Digital Design/Labs/Lab 10/Lab 10/Lab 10.srcs/sources_1/imports/sources_1/imports/sources_1/new/MUX_2_way_4_bit.vhd}
      {D:/Gimhan Sandeeptha/Gimhan/Semester 02/Computer Organization and Digital Design/Labs/Lab 10/Lab 10/Lab 10.srcs/sources_1/imports/sources_1/new/MUX_2_way_8_bit.vhd}
      {D:/Gimhan Sandeeptha/Gimhan/Semester 02/Computer Organization and Digital Design/Labs/Lab 10/Lab 10/Lab 10.srcs/sources_1/imports/new/MUX_2_way_8bit.vhd}
      {D:/Gimhan Sandeeptha/Gimhan/Semester 02/Computer Organization and Digital Design/Labs/Lab 10/Lab 10/Lab 10.srcs/sources_1/imports/new/MUX_4_8.vhd}
      {D:/Gimhan Sandeeptha/Gimhan/Semester 02/Computer Organization and Digital Design/Labs/Lab 10/Lab 10/Lab 10.srcs/sources_1/imports/new/MUX_8_8.vhd}
      {D:/Gimhan Sandeeptha/Gimhan/Semester 02/Computer Organization and Digital Design/Labs/Lab 10/Lab 10/Lab 10.srcs/sources_1/imports/sources_1/new/MUX_8_way_8_bit.vhd}
      {D:/Gimhan Sandeeptha/Gimhan/Semester 02/Computer Organization and Digital Design/Labs/Lab 10/Lab 10/Lab 10.srcs/sources_1/imports/new/Multiplier.vhd}
      {D:/Gimhan Sandeeptha/Gimhan/Semester 02/Computer Organization and Digital Design/Labs/Lab 10/Lab 10/Lab 10.srcs/sources_1/imports/sources_1/imports/new/Mux_8_to_1.vhd}
      {D:/Gimhan Sandeeptha/Gimhan/Semester 02/Computer Organization and Digital Design/Labs/Lab 10/Lab 10/Lab 10.srcs/sources_1/new/NanoProcessorLower.vhd}
      {D:/Gimhan Sandeeptha/Gimhan/Semester 02/Computer Organization and Digital Design/Labs/Lab 10/Lab 10/Lab 10.srcs/sources_1/new/NanoProcessorUpper.vhd}
      {D:/Gimhan Sandeeptha/Gimhan/Semester 02/Computer Organization and Digital Design/Labs/Lab 10/Lab 10/Lab 10.srcs/sources_1/imports/new/Out_unit.vhd}
      {D:/Gimhan Sandeeptha/Gimhan/Semester 02/Computer Organization and Digital Design/Labs/Lab 10/Lab 10/Lab 10.srcs/sources_1/imports/new/PROM.vhd}
      {D:/Gimhan Sandeeptha/Gimhan/Semester 02/Computer Organization and Digital Design/Labs/Lab 10/Lab 10/Lab 10.srcs/sources_1/imports/new/Power.vhd}
      {D:/Gimhan Sandeeptha/Gimhan/Semester 02/Computer Organization and Digital Design/Labs/Lab 10/Lab 10/Lab 10.srcs/sources_1/imports/new/Prog_counter.vhd}
      {D:/Gimhan Sandeeptha/Gimhan/Semester 02/Computer Organization and Digital Design/Labs/Lab 10/Lab 10/Lab 10.srcs/sources_1/imports/new/RCA.vhd}
      {D:/Gimhan Sandeeptha/Gimhan/Semester 02/Computer Organization and Digital Design/Labs/Lab 10/Lab 10/Lab 10.srcs/sources_1/imports/new/RCA8bit.vhd}
      {D:/Gimhan Sandeeptha/Gimhan/Semester 02/Computer Organization and Digital Design/Labs/Lab 10/Lab 10/Lab 10.srcs/sources_1/new/RCA_4.vhd}
      {D:/Gimhan Sandeeptha/Gimhan/Semester 02/Computer Organization and Digital Design/Labs/Lab 10/Lab 10/Lab 10.srcs/sources_1/imports/new/RCA_8bit.vhd}
      {D:/Gimhan Sandeeptha/Gimhan/Semester 02/Computer Organization and Digital Design/Labs/Lab 10/Lab 10/Lab 10.srcs/sources_1/imports/sources_1/imports/new/Reg.vhd}
      {D:/Gimhan Sandeeptha/Gimhan/Semester 02/Computer Organization and Digital Design/Labs/Lab 10/Lab 10/Lab 10.srcs/sources_1/imports/sources_1/new/RegBank.vhd}
      {D:/Gimhan Sandeeptha/Gimhan/Semester 02/Computer Organization and Digital Design/Labs/Lab 10/Lab 10/Lab 10.srcs/sources_1/imports/sources_1/new/Reset.vhd}
      {D:/Gimhan Sandeeptha/Gimhan/Semester 02/Computer Organization and Digital Design/Labs/Lab 10/Lab 10/Lab 10.srcs/sources_1/imports/new/Reseter.vhd}
      {D:/Gimhan Sandeeptha/Gimhan/Semester 02/Computer Organization and Digital Design/Labs/Lab 10/Lab 10/Lab 10.srcs/sources_1/imports/new/Slow_Clk.vhd}
      {D:/Gimhan Sandeeptha/Gimhan/Semester 02/Computer Organization and Digital Design/Labs/Lab 10/Lab 10/Lab 10.srcs/sources_1/imports/new/TWISTER.vhd}
      {D:/Gimhan Sandeeptha/Gimhan/Semester 02/Computer Organization and Digital Design/Labs/Lab 10/Lab 10/Lab 10.srcs/sources_1/imports/new/signed_divider.vhd}
      {D:/Gimhan Sandeeptha/Gimhan/Semester 02/Computer Organization and Digital Design/Labs/Lab 10/Lab 10/Lab 10.srcs/sources_1/imports/new/validator.vhd}
      {D:/Gimhan Sandeeptha/Gimhan/Semester 02/Computer Organization and Digital Design/Labs/Lab 10/Lab 10/Lab 10.srcs/sources_1/new/NanoProcessor.vhd}
    }
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top NanoProcessor
    rt::set_parameter enableIncremental true
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter elaborateRtlOnlyFlow true
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter enableSplitFlowPath "D:/Gimhan Sandeeptha/Gimhan/Semester 02/Computer Organization and Digital Design/Labs/Lab 10/Lab 10/.Xil/Vivado-31260-LAPTOP-J3LKM3K9/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
